// swift-tools-version:5.9
import PackageDescription

// TagLib's vendored C++ source compiles with FLAT includes (e.g. fileref.h does
// `#include "tfile.h"`) but the sources are scattered across ~25 subdirs. These
// header search paths let CTagLibCore compile its own .cpp files. Dependents do
// NOT see these; they consume the flattened public headers in include/taglib/
// (generated by scripts/generate-flat-headers.sh).
let taglibInternalHeaderPaths: [CXXSetting] = [
    .headerSearchPath("config"),
    .headerSearchPath("."),
    .headerSearchPath("include"),
    .headerSearchPath("taglib"),
    .headerSearchPath("taglib/toolkit"),
    .headerSearchPath("taglib/mpeg"),
    .headerSearchPath("taglib/mpeg/id3v1"),
    .headerSearchPath("taglib/mpeg/id3v2"),
    .headerSearchPath("taglib/mpeg/id3v2/frames"),
    .headerSearchPath("taglib/ogg"),
    .headerSearchPath("taglib/ogg/flac"),
    .headerSearchPath("taglib/ogg/vorbis"),
    .headerSearchPath("taglib/ogg/speex"),
    .headerSearchPath("taglib/ogg/opus"),
    .headerSearchPath("taglib/flac"),
    .headerSearchPath("taglib/mp4"),
    .headerSearchPath("taglib/mpc"),
    .headerSearchPath("taglib/riff"),
    .headerSearchPath("taglib/riff/aiff"),
    .headerSearchPath("taglib/riff/wav"),
    .headerSearchPath("taglib/ape"),
    .headerSearchPath("taglib/wavpack"),
    .headerSearchPath("taglib/trueaudio"),
    .headerSearchPath("taglib/asf"),
    .headerSearchPath("taglib/mod"),
    .headerSearchPath("taglib/it"),
    .headerSearchPath("taglib/s3m"),
    .headerSearchPath("taglib/xm"),
    .headerSearchPath("taglib/dsf"),
    .headerSearchPath("taglib/dsdiff"),
    .headerSearchPath("taglib/matroska"),
    .headerSearchPath("taglib/matroska/ebml"),
    .headerSearchPath("taglib/shorten"),
    .headerSearchPath("utfcpp"),
]

let package = Package(
    name: "TagLibSwift",
    platforms: [
        .iOS(.v13),
        .macOS(.v10_15)
    ],
    products: [
        // The one and only product: the full TagLib-faithful Swift API, layered
        // over TagLib's C++ types via Swift/C++ interop. Consumers must enable
        // C++ interop on their own target (see README).
        .library(
            name: "TagLibSwift",
            targets: ["TagLibSwift"]
        ),
    ],
    dependencies: [],
    targets: [
        // Vendored TagLib 2.3.1 C++ source. Compiles all .cpp and exposes the
        // flattened taglib C++ headers (include/taglib/, generated by
        // scripts/generate-flat-headers.sh) plus the taglib_interop.h helpers as
        // its public headers.
        .target(
            name: "CTagLibCore",
            path: "Sources/CTagLibCore",
            publicHeadersPath: "include",
            cxxSettings: taglibInternalHeaderPaths,
            linkerSettings: [
                .linkedLibrary("z"),
                .linkedLibrary("c++"),
            ]
        ),
        // The entire public Swift API. Rides Swift/C++ interop over CTagLibCore.
        // interoperabilityMode(.Cxx) is unconditional; any consuming target must
        // enable C++ interop as well.
        .target(
            name: "TagLibSwift",
            dependencies: ["CTagLibCore"],
            path: "Sources/TagLibSwift",
            swiftSettings: [
                .interoperabilityMode(.Cxx)
            ]
        ),
        .testTarget(
            name: "TagLibSwiftTests",
            dependencies: ["TagLibSwift"],
            path: "Tests/TagLibSwiftTests",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .interoperabilityMode(.Cxx)
            ]
        ),
    ],
    cxxLanguageStandard: .cxx17
)
